//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractHumanFactory.java
//  @ Date : 2015/12/3
//  @ Author : 
//
//



package designPattern.factory;


public abstract class AbstractHumanFactory {
	public abstract <T extends Human> T createHuman(Class<T> c);
}
