//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BlackHuman.java
//  @ Date : 2015/12/3
//  @ Author : 
//
//



package designPattern.factory;


public class BlackHuman implements Human {
	public void getColor(){
		System.out.println("黑人的肤色是黑色");
	}
	public void talk(){
		System.out.println("黑色人讲话是双字节");
	}
}
