//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HumanFactory.java
//  @ Date : 2015/12/3
//  @ Author : 
//
//



package designPattern.factory;


public class HumanFactory extends AbstractHumanFactory {

	/* (non-Javadoc)
	 * @see designPattern.factory.AbstractHumanFactory#createHuman(java.lang.Class)
	 */
	@Override
	public <T extends Human> T createHuman(Class<T> c) {
		// TODO Auto-generated method stub

		Human human=null;
		try{
			human=(Human) Class.forName(c.getName()).newInstance();
		}catch(Exception e){
			System.out.println("获取实例失败");
		}
		return (T) human;
	}
	
	
}
