//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Human.java
//  @ Date : 2015/12/3
//  @ Author : 
//
//



package designPattern.factory;


public interface Human {

	public void getColor();

	public void talk();
}
