//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NvWa.java
//  @ Date : 2015/12/3
//  @ Author : 
//
//



package designPattern.factory;


public class NvWa {
	public static void main(String[] args){

		AbstractHumanFactory yinYangLu=new HumanFactory();

		System.out.println("白人");
		Human writeHuman=yinYangLu.createHuman(WriteHuman.class);
		writeHuman.getColor();
		writeHuman.talk();

		System.out.println("\n--黑人");
		Human blackHuman=yinYangLu.createHuman(BlackHuman.class);
		blackHuman.getColor();
		blackHuman.talk();

		System.out.println("\n--黄人");
		Human yellowHuman=yinYangLu.createHuman(YellowHuman.class);
		yellowHuman.getColor();
		yellowHuman.talk();
		
	}
}
