//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WriteHuman.java
//  @ Date : 2015/12/3
//  @ Author : 
//
//



package designPattern.factory;


public class WriteHuman implements Human {
	public void getColor(){
		System.out.println("白人肤色是白色");
	}
	public void talk(){
		System.out.println("白人说话是单字节");
	}
}
