//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : YellowHuman.java
//  @ Date : 2015/12/3
//  @ Author : 
//
//



package designPattern.factory;


public class YellowHuman implements Human {
	public void getColor(){
		System.out.println("黄人的肤色是黄色");
	}
	public void talk(){
		System.out.println("黄人讲话是双字节");
	}
}
