//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractHummerModel.java
//  @ Date : 2015/12/7
//  @ Author : 
//
//

package designPattern.templateMethod.hummer;

public abstract class AbstractHummerModel {
	protected abstract void start();

	protected abstract void stop();

	protected abstract void alarm();

	protected abstract void engineBoom();

	public void run() {

		this.start();
		this.engineBoom();
		if(this.isAlarm()){
			this.alarm();
		}
		this.stop();

	}
	protected boolean isAlarm(){
		return true;
	}
	
}
