//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HummerH2Model.java
//  @ Date : 2015/12/7
//  @ Author : 
//
//



package designPattern.templateMethod.hummer;


public class HummerH2Model extends AbstractHummerModel {
	protected void start() {
		System.out.println("H2启动");
	}
	
	protected void stop() {
		System.out.println("H2停止");
	}
	
	protected void alarm() {
		System.out.println("H2喇叭响起");
	}
	
	protected void engineBoom() {
		System.out.println("H2引擎响起");
	}
	/*
	 * (non-Javadoc)
	 * @see designPattern.templateMethod.hummer.AbstractHummerModel#run()
	 * 
	 */
/*	public void run() {
		this.start();
		this.engineBoom();
		this.alarm();
		this.stop();
	}*/
	protected boolean isAlarm() {
		return false;
	}
}
