//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BWMBuilder.java
//  @ Date : 2015/12/12
//  @ Author : 
//
//



package designPattern.builder.carBuilder;

import java.util.ArrayList;


public class BWMBuilder extends CarBuilder {
	private CarModel bwmModel=new BWMModel();
	public void setSequence(ArrayList sequence) {
		this.bwmModel.setSequence(sequence);
	}
	
	public CarModel getCarModel() {
		return this.bwmModel;
	}
}
