//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CarBuilder.java
//  @ Date : 2015/12/12
//  @ Author : 
//
//



package designPattern.builder.carBuilder;

import java.util.ArrayList;


public abstract class CarBuilder {
	public abstract void setSequence(ArrayList sequence);
	public abstract CarModel getCarModel();
}
