//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CarModel.java
//  @ Date : 2015/12/12
//  @ Author : 
//
//



package designPattern.builder.carBuilder;

import java.util.ArrayList;


public abstract class CarModel {
	private ArrayList<String> sequence=new ArrayList<String>();
	public abstract void start();
	public abstract void stop();
	public abstract void alarm();
	public abstract void engineBoom();
	public void run() {
		for(int i=0;i<this.sequence.size();i++){
			if(sequence.get(i).equalsIgnoreCase("start")){
				this.start();
			}else if(sequence.get(i).equalsIgnoreCase("alarm")){
				this.alarm();
			}else if (sequence.get(i).equalsIgnoreCase("engineBoom")) {
				this.engineBoom();
			}else if (sequence.get(i).equalsIgnoreCase("stop")) {
				this.stop();
			}
		}
	}
	final public void setSequence(ArrayList<String> sequence){
		this.sequence=sequence;
	}

}
