@startuml
'https://plantuml.com/sequence-diagram

participant Alice
participant Bob
note left of Alice #aqua
This is displayed
left of Alice
end note

note right of Alice: this is displayed right of Alice
note over Alice: This is displayed over Alice
note over Alice,Bob #FFAAAA: This is displayed\nover Bob and Alice.

note over Bob,Alice
This  is yet another
example of
a long note.
end note

@enduml