//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BenzModel.java
//  @ Date : 2015/12/12
//  @ Author : 
//
//



package designPattern.builder.car;


public class BenzModel extends CarModel {
	public void start() {
		System.out.println("奔驰车启动");
	}
	
	public void stop() {
		System.out.println("奔驰车停止");
	}
	
	public void alarm() {
		System.out.println("奔驰车鸣喇叭");
	}
	
	public void engineBoom() {
		System.out.println("奔驰车引擎响起");
	}
}
