//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BWMModel.java
//  @ Date : 2015/12/12
//  @ Author : 
//
//



package designPattern.builder.car;


public class BWMModel extends CarModel {
	public void start() {
		System.out.println("宝马车启动");
	}
	
	public void stop() {
		System.out.println("宝马车停止");
	}
	
	public void alarm() {
		System.out.println("宝马车喇叭响起");
	}
	
	public void engineBoom() {
		System.out.println("宝马车引擎响起");
	}
}
