//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CarModel.java
//  @ Date : 2015/12/12
//  @ Author : 
//
//



package designPattern.builder.car;

import java.util.ArrayList;


public abstract class CarModel {
	private ArrayList<String> sequence=new ArrayList<String>();
	public abstract void start();
	public abstract void stop();
	public abstract void alarm();
	public abstract void engineBoom();
	public void run() {
		for(int i=0;i<this.sequence.size();i++){
			String actionName=this.sequence.get(i);
			if(actionName.equalsIgnoreCase("start")){
				this.start();
			}else if(actionName.equalsIgnoreCase("stop")){
				this.stop();
			}else if(actionName.equalsIgnoreCase("alarm")){
				this.alarm();
			}else if(actionName.equalsIgnoreCase("engineBoom")){
				this.engineBoom();
			}
		}
	}
	
	final public void setSequence(ArrayList sequence) {
		this.sequence=sequence;
	}
	
}
