//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Minister.java
//  @ Date : 2015/12/2
//  @ Author : 
//
//



package designPattern.singleton;

//the minister pay a formal visit the only one Emperor within 3 days
public class Minister {
	public static void main(String[] args){
		for(int day=0;day<3;day++){
			Emperor emperor=Emperor.getInstances();
			emperor.say();
		}
	}
}
