@startuml
'https://plantuml.com/use-case-diagram

User<<Human>>
:Main Database: as Mysql<<Application>>
(Start)<<One Shot>>
(Use the application) as (Use) <<Main>>
User->(Start)
User-->(Use)
Mysql-->(Use)

@enduml