@startuml
'https://plantuml.com/class-diagram

Object <|--ArrayList
Object : equals()
ArrayList : Object[] elementData
ArrayList : size()

newPage
class Dummy{
    String data;
    void methods();
}

class Flight{
    flightNumber : Integer
    departureTime : Date
}
newPage
class Dummy01{
    {field} A field (despite  parentheses)
    {method} Some method

}

@enduml