//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractBlackHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//

package designPattern.factory.maleFemale;

public abstract class AbstractBlackHuman implements
		designPattern.factory.maleFemale.IHuman {
	public void getColor(){
		System.out.println("黑人肤色是黑色");
	}

	public void talk() {
		System.out.println("黑人说话是双字节！");		
	}
}
