//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractWhiteHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//

package designPattern.factory.maleFemale;

public abstract class AbstractWhiteHuman implements
		designPattern.factory.maleFemale.IHuman {
	public void getColor(){
		System.out.println("白人的肤色是白色");
	}

	public void talk() {
		System.out.println("白人说话是双字节");		
	}
}
