//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractYellowHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//

package designPattern.factory.maleFemale;

public abstract class AbstractYellowHuman implements
		designPattern.factory.maleFemale.IHuman {
	public void getColor(){
		System.out.println("黄色人的肤色是黄色");
	}

	public void talk() {
		System.out.println("黄色人说话是双字节");		
	}

}
