//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FemaleFactory.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class FemaleFactory implements designPattern.factory.maleFemale.IHumanFactory {
	public IHuman createWhiteHuman() {
		return new FemaleWhiteHuman();
	}
	public IHuman createYellowHuman() {
		return new FemaleYellowHuman();
	}
	public IHuman createBlackHuman() {
		return new FemaleBlackHuman();
	}
}
