//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FemaleBlackHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class FemaleBlackHuman extends AbstractBlackHuman {
	
	public void getSex(){
		System.out.println("女性");
		
	}
}
