//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FemaleWhiteHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class FemaleWhiteHuman extends AbstractWhiteHuman {
	public void getSex(){
		System.out.println("女性白人");
	}
}
