//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FemaleYellowHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class FemaleYellowHuman extends AbstractYellowHuman {	
	public void getSex(){
		System.out.println("女性黄人");
	}
}
