//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IHumanFactory.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public interface IHumanFactory {
	public IHuman createWhiteHuman();
	public IHuman createYellowHuman();
	public IHuman createBlackHuman();
}
