//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaleBlackHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class MaleBlackHuman extends AbstractBlackHuman {

	
	public void getSex(){
		System.out.println("男性黑人");
	}
}
