//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaleWhiteHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class MaleWhiteHuman extends AbstractWhiteHuman {
	
	public void getSex(){
		System.out.println("男性白人");
	}
}
