//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MaleYellowHuman.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class MaleYellowHuman extends AbstractYellowHuman {

	
	public void getSex(){
		System.out.println("男性黄人");
	}
}
