//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NvWa.java
//  @ Date : 2015/12/4
//  @ Author : 
//
//



package designPattern.factory.maleFemale;


public class NvWa {
	public static void main(String[] args) {
		//男性
		IHumanFactory maleHumanFactory=new MaleFactory();
		//女性
		IHumanFactory femaleHumanFactory=new FemaleFactory();
		//男人、女人
		IHuman maleYellowHuman=maleHumanFactory.createYellowHuman();
		IHuman femaleYellowHuman=femaleHumanFactory.createYellowHuman();
		System.out.println("--女性黄人--");
		femaleYellowHuman.getColor();
		femaleYellowHuman.getSex();
		femaleYellowHuman.talk();
		System.out.println("\n--男性黄人--");		
		maleYellowHuman.getColor();
		maleYellowHuman.getSex();
		maleYellowHuman.talk();
		
		
	}
}
